### ISSUE TITLE
Can't use the migration code as we have existing data in oro_commerce_menu_upd

### ISSUE THREAD

**Issue by LaurentCampmas** [oroinc/customer-portal#1]
https://github.com/oroinc/customer-portal/blob/85d7e90b1eddc7dfccf08ab7b173cd22244d7eba/src/Oro/Bundle/CommerceMenuBundle/Migrations/Schema/v1_3/OroCommerceMenuBundle.php#L30

> Oro\Bundle\CommerceMenuBundle\Migrations\Schema\v1_3\OroCommerceMenuBundle
    ERROR: An exception occurred while executing 'ALTER TABLE oro_commerce_menu_upd ADD screens TEXT NOT NULL':

SQLSTATE[23502]: Not null violation: 7 ERROR:  column "screens" contains null values

**Comment by inri13666** [comment]
Hello, LaurentCampmas.
Thank you for reporting the issue! We greatly appreciate all contributions to Oro projects.

The task was added to fix this problem (_INTERNAL ID: BB-12857_). It will be fixed in next releases.

**Comment by anyt** [comment]
Fixed in https://github.com/oroinc/customer-portal/commit/782508b14ad2b4cd466e06aedcc91b358f37fa9d
Thank you!
