### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by xgitxhubx** [oroinc/customer-portal#2]
The class with namespace "Oro\Bundle\CustomerBundle\Migrations\Schema\v1_15\ClearLostCustomerUsers" was missing. It causes error when run the  command "oro:message-queue:consume".
File: https://github.com/oroinc/customer-portal/blob/master/src/Oro/Bundle/CustomerBundle/Resources/config/services.yml#L909
Definition:
```
oro_customer.clear_lost_customer_users_processor:
    class: Oro\Bundle\CustomerBundle\Migrations\Schema\v1_15\ClearLostCustomerUsers
```
https://github.com/oroinc/customer-portal/tree/master/src/Oro/Bundle/CustomerBundle/Migrations/Schema/v1_15
I think it is a typing error.
Should it be "Oro\Bundle\CustomerBundle\Migrations\Schema\v1_14\ClearLostCustomerUsers"?
https://github.com/oroinc/customer-portal/tree/master/src/Oro/Bundle/CustomerBundle/Migrations/Schema/v1_14

**Comment by manowark** [comment]
Hi, @xgitxhubx.
Thank you for reporting the issue! We greatly appreciate all contributions to Oro projects.
I created internal task to fix this problem (INTERNAL ID: BB-12901).

**Comment by xgitxhubx** [comment]
Thanks. It's fixed.
