### ISSUE TITLE
Question: Is oro/customer-portal tied to oro/commerce?

### ISSUE THREAD

**Issue by gplanchat** [oroinc/customer-portal#3]
Since OroCommerce 1.4, the Customer Portal has explicit dependency to `oro/commerce` in `composer.json` (https://github.com/oroinc/customer-portal/commit/d7522782b46230b5d4597d51d12ffec7120a2249). The thing is `oro/commerce` also requires `oro/customer-portal`, which creates a cyclic dependency.

Is this package supposed to continue to be an OroCommerce-exclusive frontend or should it be at some point an OroPlatform frontend, usable by OroCRM/Marello/HRroll/etc.?

**Comment by anyt** [comment]
We started decoupling of customer-portal from commerce to allow it to be used independently as a front for CRM, but it was not finished, because of changed priorities.
To don't confuse developers explicit dependency is added to `composer.json` as it represents the current state of the customer-portal package.

I will clarify with product owners, and write you back if anything changed, but as I know we don't have plans to resume work on decoupling customer-portal from commerce anytime soon.

**Comment by mbessolov** [comment]
If you are interested in making it work independently, I believe the remaing amount of required refactoring is not big - you are welcome to contribute.

**Comment by gplanchat** [comment]
Yes, I managed to use `akeneo/php-couplig-detector` and the result shows it is almost done, indeed.

```
Gregory:orocommerce-application-3.0 gplanchat$ bin/php-coupling-detector detect

Parsing 473 nodes...
Checking 35 rules...

Node /.../vendor/oro/customer-portal/src/Oro/Bundle/CustomerBundle/JsTree/CustomerTreeHandler.php does not respect the rule Oro\Bundle\CustomerBundle because of the tokens:
    * Oro\Component\Tree\Handler\AbstractTreeHandler

Node /.../vendor/oro/customer-portal/src/Oro/Bundle/CustomerBundle/Form/Extension/FrontendProductSelectExtension.php does not respect the rule Oro\Bundle\CustomerBundle because of the tokens:
    * Oro\Bundle\ProductBundle\Form\Type\ProductSelectType

Node /.../vendor/oro/customer-portal/src/Oro/Bundle/CustomerBundle/Placeholder/CustomerIdPlaceholder.php does not respect the rule Oro\Bundle\CustomerBundle because of the tokens:
    * Oro\Bundle\WebsiteSearchBundle\Placeholder\AbstractPlaceholder

Node /.../vendor/oro/customer-portal/src/Oro/Bundle/CustomerBundle/Placeholder/CustomerUserIdPlaceholder.php does not respect the rule Oro\Bundle\CustomerBundle because of the tokens:
    * Oro\Bundle\WebsiteSearchBundle\Placeholder\AbstractPlaceholder

Node /.../vendor/oro/customer-portal/src/Oro/Bundle/FrontendBundle/Form/Type/RuleEditorTextareaTypeTest.php does not respect the rule Oro\Bundle\FrontendBundle because of the tokens:
    * Oro\Bundle\PayPalBundle\PayPal\Payflow\Option\OptionsResolver
    * Oro\Bundle\PricingBundle\Form\Type\PriceRuleEditorType

Node /.../vendor/oro/customer-portal/src/Oro/Bundle/FrontendBundle/Form/Type/RuleEditorTextTypeTest.php does not respect the rule Oro\Bundle\FrontendBundle because of the tokens:
    * Oro\Bundle\PayPalBundle\PayPal\Payflow\Option\OptionsResolver
    * Oro\Bundle\PricingBundle\Form\Type\PriceRuleEditorType

Node /.../vendor/oro/customer-portal/src/Oro/Bundle/WebsiteBundle/Entity/Website.php does not respect the rule Oro\Bundle\WebsiteBundle because of the tokens:
    * Oro\Component\Website\WebsiteInterface

Node /.../vendor/oro/customer-portal/src/Oro/Bundle/WebsiteBundle/Resolver/WebsiteUrlResolver.php does not respect the rule Oro\Bundle\WebsiteBundle because of the tokens:
    * Oro\Component\Website\WebsiteInterface


8 coupling issues found ✖😥🍆
```

**Comment by gplanchat** [comment]
@mbessolov where could I send you feedback on my analysis and propositions for removing this dependency ? Is github the good place or we could discuss on Oro Partner slack ?

**Comment by clicktrend** [comment]
Hi @gplanchat, do you have any updates on this issue? I checked your fork and composer.json still requires orocommerce.

**Comment by wimg** [comment]
@gplanchat Do you know if there's any progress on this issue ? We're looking at the same problem..
